# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  required_providers {
    google = {
      source  = "hashicorp/google"
      version = "4.5.0"
    }
  }
}
provider "google" {
  project = "gcpdemo-task1"
  region  = "us-central1"
}
